[env:t-dongle-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D SDMMC_HOST_SLOT0_TIMEOUT_US=1000000
    -D ASYNCWEBSERVER_MAX_SIZE=32768
    -D ASYNCWEBSERVER_MAX_CLIENTS=8

lib_deps =
    lovyan03/LovyanGFX
    h2zero/NimBLE-Arduino
    https://github.com/ESP32Async/ESPAsyncWebServer.git
